---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 740262534431678464-IJqi5DeaBMjIEckHPh1CPWjxnuzNq3F
:access_token_secret: v74LNGGys74o2zJ2s8B3qXZZAPpgBH8JTMZpYvPVffayc
