# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ee3241d325bfa17d613a308ddd0d56b0935bae39714038ee5313dc9c8d791fb63fc3a97a162c5ff66dcaf998fdeb1f40d16952973f9a3b7b78764085093c9b0

test:
  secret_key_base: 03b5d3cf2c0de5d03006c453be999a769e4031e8f8df5987423a3e6c244d65968458e3e9a68ac4f7076409bb36e8856747548041cc54d44a1a21d39ba809e9ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
